import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight:['200', '300', '400', '500', '600', '700', '800'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className=' bg-[#0E221A] text-white '>
        <body className={`${poppins.className} `}>
          
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
